// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8zAXoRbBlUPOs8nQl00NGK0ScOq9cyc',
    appId: '1:158850493471:web:68942d1f761c9c8db2392a',
    messagingSenderId: '158850493471',
    projectId: 'real-estate-management-s-223a2',
    authDomain: 'real-estate-management-s-223a2.firebaseapp.com',
    storageBucket: 'real-estate-management-s-223a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMf0de15CjsJHeZ5qEXgG9H2R6pMVuYZo',
    appId: '1:158850493471:android:4e91219dfff68956b2392a',
    messagingSenderId: '158850493471',
    projectId: 'real-estate-management-s-223a2',
    storageBucket: 'real-estate-management-s-223a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEy763H7Ltt3p3ZCKzjrjg9ImV9-VS3Z4',
    appId: '1:158850493471:ios:ccf4a447d8578210b2392a',
    messagingSenderId: '158850493471',
    projectId: 'real-estate-management-s-223a2',
    storageBucket: 'real-estate-management-s-223a2.firebasestorage.app',
    iosBundleId: 'com.example.realEstateManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEy763H7Ltt3p3ZCKzjrjg9ImV9-VS3Z4',
    appId: '1:158850493471:ios:ccf4a447d8578210b2392a',
    messagingSenderId: '158850493471',
    projectId: 'real-estate-management-s-223a2',
    storageBucket: 'real-estate-management-s-223a2.firebasestorage.app',
    iosBundleId: 'com.example.realEstateManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8zAXoRbBlUPOs8nQl00NGK0ScOq9cyc',
    appId: '1:158850493471:web:33bfc050edb418e5b2392a',
    messagingSenderId: '158850493471',
    projectId: 'real-estate-management-s-223a2',
    authDomain: 'real-estate-management-s-223a2.firebaseapp.com',
    storageBucket: 'real-estate-management-s-223a2.firebasestorage.app',
  );
}
